### ISSUE TITLE
What is wrong with nodejs 14+?

### ISSUE THREAD

**Issue by dougg0k** [alxnkt/mongo-to-postgres#9]
You seem to have updated libs, what is wrong with using nodejs 14+?

**Comment by alxnkt** [comment]
Hello, dougg0k!

Thank you for your feedback.

When this tool was created, NodeJS 14 has just appeared (April, 2020). And I had some weird issues concerning ES6 modules. I don't think this warning is currently actual.

Best regards,
alxnkt
